### ISSUE TITLE
more easier way to pass an DBNull SqlParameter

### ISSUE THREAD

**Issue by DoraemonYu** [mirabeau-nl/Mirabeau-Sql-Helper#4]
o(∩_∩)o  Hello.
Today I began to use this library, instead of the old "optimized SqlHelper",which is also base-modify from "Microsoft .NET Data Access Application Block" .

Everything is ok. 
Just a error will throw when pass a SqlParameter ,which's value is DBNull.

Then I found out the different between two SqlHelper,and found that  in "Mirabeau-Sql-Helper" Library counld add this judge to make it same and work for my codes.
Postion is:  DatabaseHelper.cs file, AttachParameters<TParameter> methode

```
 if ((sqlParameter.Direction == ParameterDirection.InputOutput || sqlParameter.Direction == ParameterDirection.Input) && (sqlParameter.Value == null))
 {
    sqlParameter.Value = DBNull.Value;
 }
```

Main is the `sqlParameter.Direction == ParameterDirection.Input`

As we known,when we create a SqlParameter, its default value of  "Direction" property is "ParameterDirection.Input".
So, if we add the judge,it counld help developer more easier way to pass an DBNull SqlParameter  :)
Therefore, in my opinion, I suggest this library would consider to add it to TODO list.

---

Thank you sincerely.

**Comment by jeroenpot** [comment]
Hey @DoraemonYu ,

It's something which could definitly be improved. I've fixed the code you mentioned in my fork already, and i'm sure @skinds is glad to fix it in this library as well :)
